import { Knex } from "knex";
import { ETableNames } from "../ETableNames";

// Step 4: Create a seed function
export const seed = async (knex: Knex) => {
  const [{ count }] = await knex(ETableNames.cidade).count<[{ count: number }]>(
    "* as count"
  );

  if (!Number.isInteger(count) || Number(count) > 0) {
    return;
  }

  const cidadesToInsert = cidades.map((cidade) => ({
    nome: cidade.nome,
    estado: cidade.estado,
  }));
  await knex(ETableNames.cidade).insert(cidadesToInsert);
};

const cidades = [
  { nome: "Limeira", estado: "São Paulo" },
  { nome: "Rio de Janeiro", estado: "Rio de Janeiro" },
  { nome: "São Paulo", estado: "São Paulo" },
  { nome: "Belo Horizonte", estado: "Minas Gerais" },
  { nome: "Porto Alegre", estado: "Rio Grande do Sul" },
  { nome: "Curitiba", estado: "Paraná" },
  { nome: "Salvador", estado: "Bahia" },
  { nome: "Fortaleza", estado: "Ceará" },
  { nome: "Brasília", estado: "Distrito Federal" },
  { nome: "Manaus", estado: "Amazonas" },
  { nome: "Recife", estado: "Pernambuco" },
  { nome: "Belém", estado: "Pará" },
  { nome: "Goiânia", estado: "Goiás" },
  { nome: "São Luís", estado: "Maranhão" },
  { nome: "Maceió", estado: "Alagoas" },
  { nome: "Natal", estado: "Rio Grande do Norte" },
  { nome: "Teresina", estado: "Piauí" },
  { nome: "Campo Grande", estado: "Mato Grosso do Sul" },
  { nome: "João Pessoa", estado: "Paraíba" },
  { nome: "Cuiabá", estado: "Mato Grosso" },
  { nome: "Aracaju", estado: "Sergipe" },
  { nome: "Florianópolis", estado: "Santa Catarina" },
  { nome: "Palmas", estado: "Tocantins" },
  { nome: "Macapá", estado: "Amapá" },
  { nome: "Boa Vista", estado: "Roraima" },
  { nome: "Vitória", estado: "Espírito Santo" },
  { nome: "Santos", estado: "São Paulo" },
  { nome: "Campinas", estado: "São Paulo" },
  { nome: "São Bernardo do Campo", estado: "São Paulo" },
  { nome: "Osasco", estado: "São Paulo" },
  { nome: "Sorocaba", estado: "São Paulo" },
  { nome: "Ribeirão Preto", estado: "São Paulo" },
  { nome: "Santo André", estado: "São Paulo" },
  { nome: "Jundiaí", estado: "São Paulo" },
  { nome: "Piracicaba", estado: "São Paulo" },
  { nome: "Mogi das Cruzes", estado: "São Paulo" },
  { nome: "São José dos Campos", estado: "São Paulo" },
  { nome: "Franca", estado: "São Paulo" },
  { nome: "Taubaté", estado: "São Paulo" },
  { nome: "Barueri", estado: "São Paulo" },
  { nome: "Carapicuíba", estado: "São Paulo" },
  { nome: "Bauru", estado: "São Paulo" },
  { nome: "Itaquaquecetuba", estado: "São Paulo" },
  { nome: "São Vicente", estado: "São Paulo" },
  { nome: "Guarujá", estado: "São Paulo" },
  { nome: "Jacareí", estado: "São Paulo" },
  { nome: "Hortolândia", estado: "São Paulo" },
  { nome: "Sumaré", estado: "São Paulo" },
  { nome: "Indaiatuba", estado: "São Paulo" },
  { nome: "Marília", estado: "São Paulo" },
  { nome: "Suzano", estado: "São Paulo" },
  { nome: "Taboão da Serra", estado: "São Paulo" },
  { nome: "Itapecerica da Serra", estado: "São Paulo" },
  { nome: "Diadema", estado: "São Paulo" },
  { nome: "Jaboatão dos Guararapes", estado: "Pernambuco" },
  { nome: "Olinda", estado: "Pernambuco" },
  { nome: "Caruaru", estado: "Pernambuco" },
  { nome: "Petrolina", estado: "Pernambuco" },
  { nome: "Cabo de Santo Agostinho", estado: "Pernambuco" },
  { nome: "Paulista", estado: "Pernambuco" },
  { nome: "Garanhuns", estado: "Pernambuco" },
  { nome: "Serra Talhada", estado: "Pernambuco" },
  { nome: "Vitória de Santo Antão", estado: "Pernambuco" },
  { nome: "Camocim de São Félix", estado: "Pernambuco" },
  { nome: "Palmares", estado: "Pernambuco" },
  { nome: "Água Preta", estado: "Pernambuco" },
  { nome: "Escada", estado: "Pernambuco" },
  { nome: "Belo Jardim", estado: "Pernambuco" },
  { nome: "Gravatá", estado: "Pernambuco" },
  { nome: "Goiana", estado: "Pernambuco" },
  { nome: "Lajedo", estado: "Pernambuco" },
  { nome: "Bom Conselho", estado: "Pernambuco" },
  { nome: "Arcoverde", estado: "Pernambuco" },
  { nome: "Carpina", estado: "Pernambuco" },
  { nome: "Itamaracá", estado: "Pernambuco" },
  { nome: "Igarassu", estado: "Pernambuco" },
  { nome: "Catende", estado: "Pernambuco" },
  { nome: "Barreiros", estado: "Pernambuco" },
  { nome: "Ouricuri", estado: "Pernambuco" },
  { nome: "Salgueiro", estado: "Pernambuco" },
  { nome: "Pesqueira", estado: "Pernambuco" },
  { nome: "São José do Egito", estado: "Pernambuco" },
  { nome: "Santa Cruz do Capibaribe", estado: "Pernambuco" },
  { nome: "Torres", estado: "Rio Grande do Sul" },
  { nome: "Bagé", estado: "Rio Grande do Sul" },
  { nome: "Pelotas", estado: "Rio Grande do Sul" },
  { nome: "Santa Maria", estado: "Rio Grande do Sul" },
  { nome: "Canoas", estado: "Rio Grande do Sul" },
  { nome: "Novo Hamburgo", estado: "Rio Grande do Sul" },
  { nome: "Passo Fundo", estado: "Rio Grande do Sul" },
  { nome: "Bento Gonçalves", estado: "Rio Grande do Sul" },
  { nome: "Rio Grande", estado: "Rio Grande do Sul" },
  { nome: "Alvorada", estado: "Rio Grande do Sul" },
  { nome: "Sapucaia do Sul", estado: "Rio Grande do Sul" },
  { nome: "Cachoeirinha", estado: "Rio Grande do Sul" },
  { nome: "Santa Cruz do Sul", estado: "Rio Grande do Sul" },
  { nome: "Esteio", estado: "Rio Grande do Sul" },
  { nome: "Viamão", estado: "Rio Grande do Sul" },
  { nome: "Gravataí", estado: "Rio Grande do Sul" },
  { nome: "São Leopoldo", estado: "Rio Grande do Sul" },
  { nome: "Uruguaiana", estado: "Rio Grande do Sul" },
  { nome: "Santana do Livramento", estado: "Rio Grande do Sul" },
  { nome: "Guaíba", estado: "Rio Grande do Sul" },
  { nome: "Erechim", estado: "Rio Grande do Sul" },
  { nome: "Ijuí", estado: "Rio Grande do Sul" },
  { nome: "Santa Rosa", estado: "Rio Grande do Sul" },
  { nome: "Vacaria", estado: "Rio Grande do Sul" },
  { nome: "Lajeado", estado: "Rio Grande do Sul" },
  { nome: "Farroupilha", estado: "Rio Grande do Sul" },
  { nome: "Cachoeira do Sul", estado: "Rio Grande do Sul" },
  { nome: "Caxias do Sul", estado: "Rio Grande do Sul" },
  { nome: "Esteio", estado: "Rio Grande do Sul" },
  { nome: "Sapiranga", estado: "Rio Grande do Sul" },
  { nome: "São Gabriel", estado: "Rio Grande do Sul" },
  { nome: "São Borja", estado: "Rio Grande do Sul" },
  { nome: "Alegrete", estado: "Rio Grande do Sul" },
  { nome: "Cruz Alta", estado: "Rio Grande do Sul" },
  { nome: "Poa", estado: "Rio Grande do Sul" },
  { nome: "Rio Pardo", estado: "Rio Grande do Sul" },
  { nome: "Frederico Westphalen", estado: "Rio Grande do Sul" },
  { nome: "Canela", estado: "Rio Grande do Sul" },
  { nome: "Gramado", estado: "Rio Grande do Sul" },
  { nome: "Carazinho", estado: "Rio Grande do Sul" },
  { nome: "Estrela", estado: "Rio Grande do Sul" },
  { nome: "Panambi", estado: "Rio Grande do Sul" },
  { nome: "Bage", estado: "Rio Grande do Sul" },
  { nome: "Encantado", estado: "Rio Grande do Sul" },
  { nome: "Osório", estado: "Rio Grande do Sul" },
  { nome: "Torres", estado: "Rio Grande do Sul" },
  { nome: "Santa Vitória do Palmar", estado: "Rio Grande do Sul" },
  { nome: "Jaguariúna", estado: "São Paulo" },
  { nome: "Itu", estado: "São Paulo" },
  { nome: "Bragança Paulista", estado: "São Paulo" },
  { nome: "Botucatu", estado: "São Paulo" },
  { nome: "Assis", estado: "São Paulo" },
  { nome: "São Carlos", estado: "São Paulo" },
  { nome: "Avaré", estado: "São Paulo" },
  { nome: "Guarulhos", estado: "São Paulo" },
  { nome: "Itapevi", estado: "São Paulo" },
  { nome: "Tatuí", estado: "São Paulo" },
  { nome: "Pindamonhangaba", estado: "São Paulo" },
  { nome: "Itatiba", estado: "São Paulo" },
  { nome: "Atibaia", estado: "São Paulo" },
  { nome: "Amparo", estado: "São Paulo" },
  { nome: "Mogi Mirim", estado: "São Paulo" },
  { nome: "Mogi Guaçu", estado: "São Paulo" },
  { nome: "Barretos", estado: "São Paulo" },
  { nome: "Fernandópolis", estado: "São Paulo" },
  { nome: "Franco da Rocha", estado: "São Paulo" },
  { nome: "Votorantim", estado: "São Paulo" },
  { nome: "Embu das Artes", estado: "São Paulo" },
  { nome: "Cubatão", estado: "São Paulo" },
  { nome: "Araraquara", estado: "São Paulo" },
  { nome: "Catanduva", estado: "São Paulo" },
  { nome: "Itapeva", estado: "São Paulo" },
  { nome: "Presidente Prudente", estado: "São Paulo" },
  { nome: "São José do Rio Preto", estado: "São Paulo" },
  { nome: "Birigui", estado: "São Paulo" },
  { nome: "Penápolis", estado: "São Paulo" },
  { nome: "Dracena", estado: "São Paulo" },
  { nome: "Lins", estado: "São Paulo" },
  { nome: "Andradina", estado: "São Paulo" },
  { nome: "São João da Boa Vista", estado: "São Paulo" },
  { nome: "Piedade", estado: "São Paulo" },
  { nome: "Lorena", estado: "São Paulo" },
  { nome: "Campos do Jordão", estado: "São Paulo" },
  { nome: "Poá", estado: "São Paulo" },
  { nome: "Sertãozinho", estado: "São Paulo" },
  { nome: "Bebedouro", estado: "São Paulo" },
  { nome: "Leme", estado: "São Paulo" },
  { nome: "Barra Bonita", estado: "São Paulo" },
  { nome: "Garça", estado: "São Paulo" },
  { nome: "Arujá", estado: "São Paulo" },
  { nome: "Cruzeiro", estado: "São Paulo" },
  { nome: "Lorena", estado: "São Paulo" },
  { nome: "Franco da Rocha", estado: "São Paulo" },
  { nome: "Caraguatatuba", estado: "São Paulo" },
  { nome: "Ubatuba", estado: "São Paulo" },
  { nome: "Itanhaém", estado: "São Paulo" },
  { nome: "Praia Grande", estado: "São Paulo" },
  { nome: "Peruíbe", estado: "São Paulo" },
  { nome: "Nova Iguaçu", estado: "Rio de Janeiro" },
  { nome: "Niterói", estado: "Rio de Janeiro" },
  { nome: "Campos dos Goytacazes", estado: "Rio de Janeiro" },
  { nome: "Volta Redonda", estado: "Rio de Janeiro" },
  { nome: "Petrópolis", estado: "Rio de Janeiro" },
  { nome: "Duque de Caxias", estado: "Rio de Janeiro" },
  { nome: "São Gonçalo", estado: "Rio de Janeiro" },
  { nome: "Macaé", estado: "Rio de Janeiro" },
  { nome: "Teresópolis", estado: "Rio de Janeiro" },
  { nome: "Angra dos Reis", estado: "Rio de Janeiro" },
  { nome: "Resende", estado: "Rio de Janeiro" },
  { nome: "Cabo Frio", estado: "Rio de Janeiro" },
  { nome: "Nova Friburgo", estado: "Rio de Janeiro" },
  { nome: "Itaperuna", estado: "Rio de Janeiro" },
  { nome: "Barra Mansa", estado: "Rio de Janeiro" },
  { nome: "Maricá", estado: "Rio de Janeiro" },
  { nome: "Guapimirim", estado: "Rio de Janeiro" },
  { nome: "Nilópolis", estado: "Rio de Janeiro" },
  { nome: "Queimados", estado: "Rio de Janeiro" },
  { nome: "Belford Roxo", estado: "Rio de Janeiro" },
  { nome: "Araruama", estado: "Rio de Janeiro" },
  { nome: "Saquarema", estado: "Rio de Janeiro" },
  { nome: "Rio das Ostras", estado: "Rio de Janeiro" },
  { nome: "Mangaratiba", estado: "Rio de Janeiro" },
  { nome: "Paraty", estado: "Rio de Janeiro" },
  { nome: "Japeri", estado: "Rio de Janeiro" },
  { nome: "Três Rios", estado: "Rio de Janeiro" },
  { nome: "Barra do Piraí", estado: "Rio de Janeiro" },
  { nome: "São João de Meriti", estado: "Rio de Janeiro" },
  { nome: "Iguaba Grande", estado: "Rio de Janeiro" },
];
